import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Header, Footer } from "./components";
import { stories } from "./content";

export default function Home() { const featured = stories.slice(0,3); return <main><Header/>
<section className="grid-lines bg-maroon text-white"><div className="container-wide grid min-h-[680px] items-center gap-12 py-20 md:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow mb-7 text-gold">Youth. Volunteerism. Community Action.</p><h1 className="display max-w-4xl text-6xl leading-[.98] md:text-8xl">Live.<br/><span className="text-gold">Create.</span><br/>Inspire.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/75">Subang Philippines is a youth-led volunteer organization committed to transforming communities into safer, equitable, sustainable, and resilient communities.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/about" className="bg-gold px-6 py-4 font-extrabold text-maroon">Discover Subang <ArrowUpRight className="inline" size={17}/></Link><Link href="/programs" className="border border-white/35 px-6 py-4 font-extrabold">Explore our work</Link></div></div><div className="relative min-h-[390px] overflow-hidden bg-blue p-8"><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full border-[55px] border-gold/80"/><div className="absolute bottom-8 left-8 right-8 border-l-2 border-gold pl-5"><p className="eyebrow text-gold">Our proposition</p><p className="mt-3 max-w-sm text-3xl font-extrabold leading-tight">Development also belongs to people willing to give their time, skills, ideas, and hands.</p></div></div></div></section>
<section className="container-wide grid gap-12 py-24 md:grid-cols-2 md:py-32"><div><p className="eyebrow text-green">01 / Who we are</p><h2 className="display mt-5 text-5xl leading-tight text-maroon md:text-6xl">People who care enough to show up.</h2></div><div className="self-end text-lg leading-8 text-ink/70"><p>Subang brings together young people, volunteers, communities, schools, local governments, and partner institutions to turn ideas into practical community action.</p><p className="mt-5">Our work spans environmental sustainability, climate and disaster resilience, youth participation, education, food security, community development, and volunteerism.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 font-extrabold text-blue">Learn our story <ArrowUpRight size={16}/></Link></div></section>
<section className="bg-white py-24"><div className="container-wide"><p className="eyebrow text-green">02 / What we do</p><div className="mt-5 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="display text-5xl text-maroon md:text-6xl">From intention<br/>to community action.</h2><Link href="/programs" className="font-extrabold text-blue">View all programs ↗</Link></div><div className="mt-14 grid gap-px bg-maroon/15 md:grid-cols-2">{[
["01","Environmental Sustainability"],["02","Food Security & Sustainable Agriculture"],["03","Youth Leadership & Participation"],["04","Education & Capacity Building"]].map(([n,t])=><Link key={n} href="/programs" className="bg-white p-9 transition hover:bg-cream"><span className="eyebrow text-green">{n}</span><h3 className="display mt-16 text-3xl text-maroon">{t}</h3><p className="mt-4 text-ink/65">Explore practical initiatives built around community needs, volunteer action, and sustainable development.</p></Link>)}</div></div></section>
<section className="bg-gold py-24"><div className="container-wide"><p className="eyebrow text-maroon/70">03 / Documented milestones</p><h2 className="display mt-5 max-w-4xl text-5xl text-maroon md:text-7xl">A movement measured by action, not just intention.</h2><div className="mt-16 grid gap-8 border-t border-maroon/25 pt-8 sm:grid-cols-2 lg:grid-cols-5"><div><p className="display text-5xl text-maroon">2023</p><p className="mt-2 font-bold">Founded</p></div><div><p className="display text-5xl text-maroon">10+</p><p className="mt-2 font-bold">Years of founder volunteerism</p></div><div><p className="display text-5xl text-maroon">300+</p><p className="mt-2 font-bold">Initiatives in organizational impact records*</p></div><div><p className="display text-5xl text-maroon">1,200+</p><p className="mt-2 font-bold">Direct beneficiaries in documented program data*</p></div><div><p className="display text-5xl text-maroon">7+</p><p className="mt-2 font-bold">Universities / academic communities</p></div></div><p className="mt-8 max-w-3xl text-xs leading-6 text-maroon/70">*Figures represent documented program and organizational records and should be periodically consolidated and updated. They are not presented as independently audited national statistics.</p></div></section>
<section className="container-wide py-24 md:py-32"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-green">04 / Stories & Press</p><h2 className="display mt-5 text-5xl text-maroon md:text-6xl">The work behind the work.</h2></div><Link href="/stories" className="font-extrabold text-blue">See all stories ↗</Link></div><div className="mt-12 grid gap-7 md:grid-cols-3">{featured.map(s=><article key={s.slug} className="overflow-hidden border border-maroon/10 bg-white"><div className="aspect-[4/3] bg-cream"><img src={s.image} alt="" className="h-full w-full object-cover"/></div><div className="p-7"><p className="eyebrow text-green">{s.type} · {s.date}</p><h3 className="display mt-4 text-2xl text-maroon">{s.title}</h3><p className="mt-4 text-sm leading-6 text-ink/65">{s.excerpt}</p><Link href={`/stories/${s.slug}`} className="mt-6 inline-flex items-center gap-2 font-extrabold text-blue">Read story <ArrowUpRight size={15}/></Link></div></article>)}</div></section>
<section className="bg-blue py-24 text-white"><div className="container-wide grid gap-10 md:grid-cols-2"><div><p className="eyebrow text-gold">05 / Join the movement</p><h2 className="display mt-5 text-5xl md:text-7xl">There is work to do. Let's do it together.</h2></div><div className="self-end"><p className="text-lg leading-8 text-white/75">Whether you are a young leader, volunteer, institution, local government, community, or potential partner, there is a place for meaningful collaboration.</p><Link href="/connect" className="mt-8 inline-flex items-center gap-3 bg-gold px-6 py-4 font-extrabold text-maroon">Connect with Subang <ArrowUpRight size={18}/></Link></div></div></section><Footer/></main> }
